class Item {
  String itemId,
      type,
      snmpOid,
      hostId,
      name,
      delay,
      history,
      trends,
      status,
      valueType,
      templateId,
      inventoryLink,
      statusCodes,
      error,
      description,
      lastClock,
      lastNs,
      lastValue,
      prevValue;

  Item({
    required this.itemId,
    required this.type,
    required this.snmpOid,
    required this.hostId,
    required this.name,
    required this.delay,
    required this.history,
    required this.trends,
    required this.status,
    required this.valueType,
    required this.templateId,
    required this.inventoryLink,
    required this.statusCodes,
    required this.error,
    required this.description,
    required this.lastClock,
    required this.lastNs,
    required this.lastValue,
    required this.prevValue,
  });

  Map<String, dynamic> toMap() {
    return {
      'itemid': itemId,
      'type': type,
      'snmp_oid': snmpOid,
      'hostid': hostId,
      'name': name,
      'delay': delay,
      'history': history,
      'trends': trends,
      'status': status,
      'value_type': valueType,
      'templateid': templateId,
      'inventory_link': inventoryLink,
      'status_codes': statusCodes,
      'error': error,
      'description': description,
      'lastclock': lastClock,
      'lastns': lastNs,
      'lastvalue': lastValue,
      'prevvalue': prevValue,
    };
  }

  factory Item.fromJson(Map<String, dynamic>? json) {
    if (json != null && json.isNotEmpty) {
      return Item(
        itemId: json['itemid'],
        type: json['type'],
        snmpOid: json['snmp_oid'],
        hostId: json['hostid'],
        name: json['name'],
        delay: json['delay'],
        history: json['history'],
        trends: json['trends'],
        status: json['status'],
        valueType: json['value_type'],
        templateId: json['templateid'],
        inventoryLink: json['inventory_link'],
        statusCodes: json['status_codes'],
        error: json['error'],
        description: json['description'],
        lastClock: json['lastclock'],
        lastNs: json['lastns'],
        lastValue: json['lastvalue'],
        prevValue: json['prevvalue'],
      );
    } else {
      return Item(
        itemId: '0',
        type: '0',
        snmpOid: '',
        hostId: '0',
        name: '',
        delay: '',
        history: '',
        trends: '0',
        status: '0',
        valueType: '0',
        templateId: '0',
        inventoryLink: '0',
        statusCodes: '0',
        error: '',
        description: '',
        lastClock: '0',
        lastNs: '0',
        lastValue: '0',
        prevValue: '0',
      );
    }
  }
}
